alcatraz/Alcatraz

Alcatraz/Controllers/ATZPluginWindowController.m

The search field predicated appeared to match based on the name of the plugins (ATZPackage) objects but was not matching on the Summary attribute. Instead it was matching on "description" which seemed to return no further results.

Small fix to the search field predicate to include 'summary' field

---

index.html

because that's how you get raw files from github now.

change raw.github.com to raw.githubusercontent.com

---

Alcatraz/Installers/ATZPluginInstaller.m

Added `clean` argument to `xcodebuild` to clean the build products before building the plugin.
This fix resolves the issue with my plugin [BBUncrustifyPlugin](https://github.com/benoitsan/BBUncrustifyPlugin-Xcode). I tested it and now the xib file is correctly copied.

clean the build directory when executing xcodebuild for issue #250

---

Alcatraz/Helpers/ATZStyleKit.m

This is a minor improvement on the buttons drawing. Instead of changing the text color mid-progress, it is animated to follow the background color:
Before:
After:

Smooths ATZFillableButton's text color change

---

Alcatraz.xcodeproj/project.pbxproj
Alcatraz/ATZPluginWindowController.xib
Alcatraz/ATZSegmentedCell.h
Alcatraz/ATZSegmentedCell.m

Fixes #226.
This PR fixes the ATZSegmentedControl's focus ring by drawing it around the blue text background. This also fixes the click area, which for some of the segments was not aligned with the custom drawn button (ie. by clicking on the far left and right ends of one segment you'd actually activate another segment).
A couple of points:
- This is probably a bit more hacky than the previous implementation:
- ATZSegmentedControl's `initWithCoder:` is overridden to work around an IB bug (https://mikeash.com/pyblog/custom-nscells-done-right.html);
- ATZSegmentedCell's `_drawBackgroundWithFrame:inView:` is overridden to do nothing, in order to disable the NSSegmentedCell's implementation, which draws the classic OS X NSSegmentedControl background;
- This is better than before, but still …

Fix ATZSegmentedControl's focus ring and click area

---

README.md

Accidental copying and pasting may result in users `rm -rf`-ing the support files but also their current directory (if they accidentally copy the "." as well, as I almost did!)
Very minor (1 character) change, but very major repercussions :)

Removed period after `rm -rf` tutorial command

---

Alcatraz/Alcatraz.m

The plugin itself always loads as can be noted in the console, but the menu item would intermittently fail to appear.
There seems to be a (common) edge case where the subscription to the notification would be deferred until after the notification is fired. This change fixes it by subscribing immediately upon initialization and
then deferring the menu item creation block instead as may be needed.
Fixes #381, #380, #379

Subscribe to Xcode launch notification synchronously

---

Scripts/install.sh

Related to #281, #282, #303 and probably a whole bunch of other issues.
This is very similar #282, but just removes Alcatraz from the skipped plugins list instead of un-blocking everything.
I also took the chance to add ["strict flags"](http://redsymbol.net/articles/unofficial-bash-strict-mode/) to the sh script, and echoing the current selected version of Xcode after install.

Remove Alcatraz from Xcode skipped plugins list on install

---

Alcatraz/Helpers/ATZPBXProjParser.m
Alcatraz/Installers/ATZPluginInstaller.m

Xcode has multiple types of plugin prefixes. Most plugins are xcplugins and can be installed in `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins`, but ideplugins have to be installed in `~/Library/Developer/Xcode/Plug-ins`. [KSImageNamed](https://github.com/ksuther/KSImageNamed-Xcode) switched from being an xcplugin to an ideplugin, so Alcatraz no longer shows it as installed.
`pathForInstalledPackage:` will now detect if it's dealing with an ideplugin that is installed and change the path to the correct one.

Added correct detection of installed ideplugins

---

Scripts/install.sh

Fix https://github.com/alcatraz/Alcatraz/issues/392 #394 
If Xcode never loaded any plugin, the `DVTPlugInManagerNonApplePlugIns-Xcode-$xcode_version` does not exist, and the script halted on the line 
```
defaults read -app Xcode "$PLIST_PLUGINS_KEY" > "$TMP_FILE"
```
We now check the return code of `default read` before continuing.
Sorry about that :/

Fix install script when no plugin was ever installed in Xcode

---

Alcatraz/Packages/ATZPackage.m

Removing this makes it possible to compile the business logic parts of Alcatraz without AppKit.

Remove unused import

---

Alcatraz.xcodeproj/project.pbxproj
Alcatraz/ATZPluginWindowController.xib
Alcatraz/Controllers/ATZPackageTableViewDelegate.m
Alcatraz/Controllers/ATZPluginWindowController.m
Alcatraz/Helpers/ATZStyleKit.h
Alcatraz/Helpers/ATZStyleKit.m
Alcatraz/Helpers/ATZXcodePrefsManager.h
Alcatraz/Helpers/ATZXcodePrefsManager.m
Alcatraz/Installers/ATZInstaller.h
Alcatraz/Installers/ATZInstaller.m
Alcatraz/Installers/ATZPluginInstaller.m
Alcatraz/Installers/ATZTemplateInstaller.m
Alcatraz/Packages/ATZPackage.h
Alcatraz/Packages/ATZPackage.m
Alcatraz/Views/ATZFillableButton.h
Alcatraz/Views/ATZFillableButton.m

Fixes #283.
Basically this:
- Displays blocked plugins in the list with a special orange "BLOCKED" button;
- Allows the user to whitelist (unblock) plugins by clicking this button;
- Add a filter option to show only blocked plugins in the segmented control, with a count of the blocked plugins (the filter option is only shown if you have blocked plugins on your machine).
Comments and code review are obviously very welcome :)

Display blocked plugins

---

CHANGELOG.md

As this is a new feature, I reckon we'll update the _minor_ version number, hence `1.2.0`.
I kept it short, let me know if you think this warrants a more detailed changelog entry.

Update CHANGELOG for #303

---

Alcatraz/Helpers/ATZGit.h
Alcatraz/Helpers/ATZGit.m

This expands the check for command line tools to include `/usr/local` as well as `/usr`.
Fixes #406, #137, #152 on fresh installations of El Capitan and Yosemite.

[ATZGit] Check possible git executable paths

---

Scripts/install.sh

This adresses two issues:
It silences the warning 
> The domain/default pair of (com.apple.dt.Xcode, DVTPlugInManagerNonApplePlugIns-Xcode-7.2) does not exist
already identified in #393. Hiding this error is fine, as it will only appear when the user never installed a plugin before.
The problem is by using `2> /dev/null` we're effectively silencing all other errors which might occur. If you have any idea how to prevent this, I'll amend the commit.
--------------
It uses `xcode-select` to know where to look for the Xcode app, instead of assuming `/Applications/Xcode.app`. This fixes the error
> Couldn't find an application named "Xcode" defaults unchanged
brought up by @drduan in #419.
I'm not very satisfied with the `sed` bit to trim out the `/Contents/Developer` part of the path returned …

Fix install script's defaults read command

---

Scripts/install.sh

Hi,
if stderr is not redirected to the tmp file the output the script tries to match in the else clause will never be there.

Redirect stderr to the temp file used in the install script.

---

Alcatraz/Helpers/ATZPBXProjParser.m

If any plugin name includes "." character such like "R.swift", the installation process will be interrupt at 100%.
Because the name parsing error causes loading bundle failed

Fix a name parsing issue if the plugin name includes any '.' character

---

Alcatraz/ATZPluginWindowController.xib
Alcatraz/Controllers/ATZPluginWindowController.h
Alcatraz/Controllers/ATZPluginWindowController.m

This is a small UI improvement for the Options menu.
- Adds a down arrow on the right of the cog icon to make it clear the button will display a dropdown menu
- Fix the indentation of the menu items to match the other OS X dropdowns
- Move the version label to the menu
The reasons for the version label move are:
- Most users don't care which version of Alcatraz they're using...
- ... and if they do, they can still find the info easily. But always showing the version number is not necessary.
- It makes space in the window, which I intend to use to display loading and error indicators (for #325, amongst others)
Here's a before / after, and an OS X dropdown for comparison:

Fix the Options menu UI

---

README.md

As remarked in #457.
Did not realize pullapprove meant we could no longer push to `master`.
I feel a bit silly opening a PR for that 😀
Btw, shouldn't we protect `gh-pages` with pullapprove too?

Add myself to the 'Team' section of README.md :)

---

Alcatraz/Helpers/ATZGit.h
Alcatraz/Helpers/ATZGit.m

Repositories using submodules need to be cloned recursively.
For example, https://github.com/mralexgray/DVTPlugInCompatibilityUUIDifier would fail to build because its AHLaunchCtl submodule was not cloned.

Clone git repositories with the --recursive option

---

.pullapprove.yml

Hey everybody -- don't want to butt in here but I noticed that PullApprove isn't detecting all of your 👍 's in comments. This should hopefully fix some of that.
A little while ago GitHub changed their UI so that when you type `:` and then pick an emoji from the autocomplete, it inserts the actual Unicode instead of just a `:+1:` string. We made some changes on PullApprove so that people wouldn't have to add Unicode to their yml (`\U0001f44d`), but the `:\+1:` needs to be in the regex in one piece for that to work automatically. I just changed the way your regexes were written so that that is the case.

Modify .pullapprove.yml regex

---

Alcatraz/Controllers/ATZPackageTableViewDelegate.m
CHANGELOG.md

This fixes the crash "Cannot lock focus on image because it is size zero". We won't attempt to display invalid images anymore.
The origin of the invalid image data is still not 100% clear though, but I suspect that the lack of error handling in ATZDownloader (the `error` param of the completion block is always `nil`) might be it.
I'll fix that in another PR when I have more time, and when we get to the root of the problem with @piv199 in https://github.com/alcatraz/Alcatraz/issues/479.
Fixes #320 #334 #335 #479.

Verify the images we download are valid before displaying them

---

Alcatraz.xcodeproj/project.pbxproj
Alcatraz/Controllers/ATZPluginWindowController.m
Alcatraz/Helpers/ATZShell.h
Alcatraz/Helpers/ATZShell.m
Alcatraz/Installers/ATZInstaller.h
Alcatraz/Installers/ATZPluginInstaller.m
CHANGELOG.md

The "Make the Mac Great Again" plugin [would not install](http://twitter.com/zorn/status/737448880472743940) because Alcatraz assumes that the .xcodeproj has the exact same name as the package. This may not be true, for example "Make the Mac Great Again" xcodeproj file is "MakeTheMacGreatAgain.xcodeproj" (without the spaces).
This new heuristic searches for all .xcodeproj and works fine if only one exists in the cloned directory.
I also refactor error handling for better diagnostics when things go wrong.

Better heuristic for finding the .xcodeproj directory

---

CHANGELOG.md

- Add mention of Xcode 8 support, with ref to #475
- Remove version 1.2.0 which we never got around to release, and move its content under `## Unreleased`

Update CHANGELOG.md with Xcode 8 support

---

Alcatraz/Alcatraz-Info.plist

I tried with Xcode 8.2.1 and it works too as it already discussed here: https://github.com/alcatraz/Alcatraz/issues/498

Add Xcode 8.2 compatibility UUID
